{% set version = "0.11.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-taxonomizr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/taxonomizr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/taxonomizr/taxonomizr_{{ version }}.tar.gz
  sha256: 4aa09a0275976cf52b2e2356b0006228d8e20977b29e36ebfcc18fe2f8154a1a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-rsqlite
    - r-curl
    - r-data.table
  run:
    - r-base
    - r-r.utils
    - r-rsqlite
    - r-curl
    - r-data.table

test:
  commands:
    - $R -e "library('taxonomizr')"           # [not win]
    - "\"%R%\" -e \"library('taxonomizr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=taxonomizr
  license: GPL-2.0-or-later
  summary: Functions for assigning taxonomy to NCBI accession numbers and taxon IDs based on NCBI's accession2taxid and taxdump files. This package allows the user to downloads NCBI data dumps and create a local database for fast and local taxonomic assignment.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: taxonomizr
# Maintainer: Scott Sherrill-Mix <shescott@upenn.edu>
# License: GPL (>= 2) | file LICENSE
# Title: Functions to Work with NCBI Accessions and Taxonomy
# Type: Package
# LazyLoad: yes
# Author: Scott Sherrill-Mix [aut, cre]
# Authors@R: c(person("Scott", "Sherrill-Mix", role = c("aut", "cre"), email = "shescott@upenn.edu"))
# BugReports: https://github.com/sherrillmix/taxonomizr/issues
# Description: Functions for assigning taxonomy to NCBI accession numbers and taxon IDs based on NCBI's accession2taxid and taxdump files. This package allows the user to downloads NCBI data dumps and create a local database for fast and local taxonomic assignment.
# Version: 0.8.0
# Date: 2021-05-05
# Suggests: testthat, knitr, rmarkdown
# Depends: R (>= 3.0.0)
# Imports: RSQLite, R.utils, data.table, curl
# RoxygenNote: 7.1.1
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2021-05-05 15:26:16 UTC; scott
# Repository: CRAN
# Date/Publication: 2021-05-06 23:20:02 UTC
